### ISSUE TITLE
LICENSE: add license to the top level directory and to the app

### ISSUE THREAD

**Issue by tixxdz** [BackPackerDz/Android-Tariki.dz#1]
Hi,
- [x] The project should include a license visible at the top level directory of the repo. The license should of course be compatible with third party API Tariki.dz and openstreetmap. Note: here you should be careful on the license, most android apps use apache, and it should be compatible with others especially GPL only in a one way, and since you will just communicate with it not link to it, however the Apache is liberal mostly like the BSD one, so every one can redistribute your work but they have to include your copyright. Please double check here ;-) 
  Personally: I would go with Apache and let it be accessible unless you have other plans ;-) 
- [x] Readme.md should also have a legal note and a license section at the bottom.
- [x] The app should also have a menu or something like this: https://www.bignerdranch.com/blog/open-source-licenses-and-android/  where you list your license , tariki.dz rights and maybe openstreetmap rights too.
- [x] Please add your copyright and name to all source files that you coded, on top of each source file. 

Thx for the work khou ;-) , and this should protect your work and tariki.dz work and rights too.

Bittewfik

**Comment by tixxdz** [comment]
Hi again, just an update on this one, personally I try to write code that's under only GPL license, but for android I am not sure... if it's a simple useful app, I would go with Apache, if I am planning something bigger I would think twice, really. Thanks again.

**Comment by BackPackerDz** [comment]
Hi, thank you very much for your help, like you see I'm a newbie !
As regards Android, most of librairies or apps I see are under Apache, but maybe I'm wrong !

**Comment by tixxdz** [comment]
@BackPackerDz you are welcome, yes it seems that Apache is the most popular one, but you may take your time and explore other licenses especially if you are planning to make it a long term project!

**Comment by BackPackerDz** [comment]
![screenshot_20160824-123112](https://cloud.githubusercontent.com/assets/8436726/17929268/3e8ee28e-69f7-11e6-9e2d-d4ca52e67daf.png)
![screenshot_20160824-123114](https://cloud.githubusercontent.com/assets/8436726/17929269/3eb4cc06-69f7-11e6-829a-fea119a5fc3b.png)
![screenshot_20160824-123116](https://cloud.githubusercontent.com/assets/8436726/17929270/3ebffd56-69f7-11e6-9c9c-aeb5d43ff769.png)

**Comment by BackPackerDz** [comment]
I add a menu in the app that show licenses but I don't know what I have to show for Tariki.dz

**Comment by tixxdz** [comment]
@BackPackerDz seems fine, I would suggest to show a small "about" for any included or third party software, and a link to their page. So for example for tariki.dz (which I don't have access to right now... only available from algeria IP addresses...) You can copy their "about" just 3 or 4 lines + a link to their webpage +  a small thanks to Gendarmerie for the service message, keep them happy and maybe there will be further realtime updates , I hope they will do ;-)

Note: if any third party software doesn't show any license, then don't add one, just "about" + link to their URL.

Seems really nice, thanks!
